module VerifyExamples.Widget.AsItem0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Widget.Material as Material
import Element







spec0 : Test.Test
spec0 =
    Test.test "#asItem: \n\n    Element.text \"Just a text\"\n        |> Widget.asItem\n        |> List.singleton\n        |> Widget.itemList (Material.cardColumn Material.defaultPalette)\n        |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                Element.text "Just a text"
                    |> Widget.asItem
                    |> List.singleton
                    |> Widget.itemList (Material.cardColumn Material.defaultPalette)
                    |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )