module VerifyExamples.Widget.Button0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Widget.Icon as Icon
import Material.Icons.Types exposing (Coloring(..))
import Material.Icons as MaterialIcons
import Widget.Material as Material

type Msg
    = Submit





spec0 : Test.Test
spec0 =
    Test.test "#button: \n\n    button (Material.containedButton Material.defaultPalette)\n        { text = \"Submit\"\n        , icon = MaterialIcons.favorite |> Icon.elmMaterialIcons Color\n        , onPress = Just Submit\n        }\n        |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                button (Material.containedButton Material.defaultPalette)
                    { text = "Submit"
                    , icon = MaterialIcons.favorite |> Icon.elmMaterialIcons Color
                    , onPress = Just Submit
                    }
                    |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )