module VerifyExamples.Widget.CircularProgressIndicator0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Widget.Material as Material







spec0 : Test.Test
spec0 =
    Test.test "#circularProgressIndicator: \n\n    Just 0.75\n    |> Widget.circularProgressIndicator (Material.progressIndicator Material.defaultPalette)\n    |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                Just 0.75
                |> Widget.circularProgressIndicator (Material.progressIndicator Material.defaultPalette)
                |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )