module VerifyExamples.Widget.Dialog0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Element
import Widget.Material as Material

type Msg
    = Submit
    | Close





spec0 : Test.Test
spec0 =
    Test.test "#dialog: \n\n    Element.layout\n        (dialog (Material.alertDialog Material.defaultPalette)\n            { title = Just \"Accept\"\n            , text = \"Are you sure?\"\n            , accept =\n                { text = \"Accept\"\n                , onPress = Just Submit\n                }\n                |> Just\n            , dismiss =\n                { text = \"Cancel\"\n                , onPress = Just Close\n                }\n                |> Just\n            }\n        )\n        |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                Element.layout
                    (dialog (Material.alertDialog Material.defaultPalette)
                        { title = Just "Accept"
                        , text = "Are you sure?"
                        , accept =
                            { text = "Accept"
                            , onPress = Just Submit
                            }
                            |> Just
                        , dismiss =
                            { text = "Cancel"
                            , onPress = Just Close
                            }
                            |> Just
                        }
                    )
                    |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )