module VerifyExamples.Widget.IconButton0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Widget.Icon as Icon
import Material.Icons.Types exposing (Coloring(..))
import Material.Icons as MaterialIcons
import Widget.Material as Material

type Msg
    = Like





spec0 : Test.Test
spec0 =
    Test.test "#iconButton: \n\n    iconButton (Material.iconButton Material.defaultPalette)\n        { text = \"Like\"\n        , icon = MaterialIcons.favorite |> Icon.elmMaterialIcons Color\n        , onPress = Just Like\n        }\n        |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                iconButton (Material.iconButton Material.defaultPalette)
                    { text = "Like"
                    , icon = MaterialIcons.favorite |> Icon.elmMaterialIcons Color
                    , onPress = Just Like
                    }
                    |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )