module VerifyExamples.Widget.InsetItem0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Widget.Material as Material
import Element







spec0 : Test.Test
spec0 =
    Test.test "#insetItem: \n\n    [ Widget.insetItem (Material.insetItem Material.defaultPalette)\n        { onPress = Nothing\n        , icon = always Element.none\n        , text = \"Item\"\n        , content = always Element.none\n        }\n    , Widget.divider (Material.insetDivider Material.defaultPalette )\n    , Widget.insetItem (Material.insetItem Material.defaultPalette)\n        { onPress = Nothing\n        , icon = always Element.none\n        , text = \"Item\"\n        , content = always Element.none\n        }\n    ]\n        |> Widget.itemList (Material.cardColumn Material.defaultPalette)\n        |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                [ Widget.insetItem (Material.insetItem Material.defaultPalette)
                    { onPress = Nothing
                    , icon = always Element.none
                    , text = "Item"
                    , content = always Element.none
                    }
                , Widget.divider (Material.insetDivider Material.defaultPalette )
                , Widget.insetItem (Material.insetItem Material.defaultPalette)
                    { onPress = Nothing
                    , icon = always Element.none
                    , text = "Item"
                    , content = always Element.none
                    }
                ]
                    |> Widget.itemList (Material.cardColumn Material.defaultPalette)
                    |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )