module VerifyExamples.Widget.Radio0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Widget.Material as Material

type Msg
    = Activate





spec0 : Test.Test
spec0 =
    Test.test "#radio: \n\n    radio (Material.radio Material.defaultPalette)\n        { description = \"Dark Mode\"\n        , onPress = Just Activate\n        , selected = False\n        }\n        |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                radio (Material.radio Material.defaultPalette)
                    { description = "Dark Mode"
                    , onPress = Just Activate
                    , selected = False
                    }
                    |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )