module VerifyExamples.Widget.Row0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Widget.Material as Material
import Element







spec0 : Test.Test
spec0 =
    Test.test "#row: \n\n    [ Element.text \"Text 1\"\n    , Element.text \"Text 2\"\n    ]\n        |> Widget.row Material.row\n        |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                [ Element.text "Text 1"
                , Element.text "Text 2"
                ]
                    |> Widget.row Material.row
                    |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )