module VerifyExamples.Widget.Switch0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Material.Icons as MaterialIcons
import Widget.Material as Material

type Msg
    = Activate





spec0 : Test.Test
spec0 =
    Test.test "#switch: \n\n    switch (Material.switch Material.defaultPalette)\n        { description = \"Activate Dark Mode\"\n        , onPress = Just Activate\n        , active = False\n        }\n        |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                switch (Material.switch Material.defaultPalette)
                    { description = "Activate Dark Mode"
                    , onPress = Just Activate
                    , active = False
                    }
                    |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )