module VerifyExamples.Widget.TextButton0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Widget exposing (..)
import Widget.Material as Material

type Msg
    = Like





spec0 : Test.Test
spec0 =
    Test.test "#textButton: \n\n    textButton (Material.textButton Material.defaultPalette)\n        { text = \"Like\"\n        , onPress = Just Like\n        }\n        |> always \"Ignore this line\"\n    --> \"Ignore this line\"" <|
        \() ->
            Expect.equal
                (
                textButton (Material.textButton Material.defaultPalette)
                    { text = "Like"
                    , onPress = Just Like
                    }
                    |> always "Ignore this line"
                )
                (
                "Ignore this line"
                )